---
apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
kind: Pod
metadata:
  name: <pod_name>
  namespace: testing
spec:
  containers:
  - name: pov-container
    image: ghcr.io/<user_name>/<container_name>:<tag>
  imagePullSecrets:
  - name: <pull-secret>
